export const SAMPLE_PRODUCTS = [
  {
    id: "p1",
    name: "Premium Smartphone",
    category: "Electronics",
    price: 799,
    stock: 25,
    status: "Active",
    desc: "Premium Smartphone with latest features",
    img: "https://picsum.photos/seed/p1/200/140",
  },
  {
    id: "p2",
    name: "Ultra Laptop",
    category: "Electronics",
    price: 120,
    stock: 50,
    status: "Inactive",
    desc: "Ultra Laptop-themed Hoodie",
    img: "https://picsum.photos/seed/p2/200/140",
  },
  {
    id: "p3",
    name: "Eco Headphones",
    category: "Electronics",
    price: 199,
    stock: 0,
    status: "Inactive",
    desc: "Eco Headphones for everyday use",
    img: "https://picsum.photos/seed/p3/200/140",
  },
  {
    id: "p4",
    name: "Classic Jeans",
    category: "Clothing",
    price: 59,
    stock: 0,
    status: "Inactive",
    desc: "Classic Jeans for casual wear",
    img: "https://picsum.photos/seed/p4/200/140",
  },
  {
    id: "p5",
    name: "Modern Camera",
    category: "Electronics",
    price: 499,
    stock: 15,
    status: "Active",
    desc: "Modern Camera with high resolution",
    img: "https://picsum.photos/seed/p5/200/140",
  },
  {
    id: "p6",
    name: "Stylish Sneakers",
    category: "Clothing",
    price: 89,
    stock: 35,
    status: "Inactive",
    desc: "Stylish Sneakers for daily use",
    img: "https://picsum.photos/seed/p6/200/140",
  },
  {
    id: "p7",
    name: "Portable Smartwatch",
    category: "Electronics",
    price: 249,
    stock: 40,
    status: "Active",
    desc: "Portable Smartwatch with GPS",
    img: "https://picsum.photos/seed/p7/200/140",
  },
  {
    id: "p8",
    name: "Deluxe Jacket",
    category: "Clothing",
    price: 150,
    stock: 20,
    status: "Inactive",
    desc: "Deluxe Jacket for winter",
    img: "https://picsum.photos/seed/p8/200/140",
  },
  {
    id: "p9",
    name: "Pro Tablet",
    category: "Electronics",
    price: 399,
    stock: 0,
    status: "Active",
    desc: "Pro Tablet for work and play",
    img: "https://picsum.photos/seed/p9/200/140",
  },
  {
    id: "p10",
    name: "Comfort Hoodie",
    category: "Clothing",
    price: 70,
    stock: 60,
    status: "Inactive",
    desc: "Comfort Hoodie for casual days",
    img: "https://picsum.photos/seed/p10/200/140",
  },
  {
    id: "p11",
    name: "Premium Speaker",
    category: "Electronics",
    price: 149,
    stock: 30,
    status: "Active",
    desc: "Premium Speaker with rich sound",
    img: "https://picsum.photos/seed/p11/200/140",
  },
  {
    id: "p12",
    name: "Eco Dress",
    category: "Clothing",
    price: 65,
    stock: 25,
    status: "Inactive",
    desc: "Eco-friendly Dress for summer",
    img: "https://picsum.photos/seed/p12/200/140",
  },
  {
    id: "p13",
    name: "Classic Monitor",
    category: "Electronics",
    price: 299,
    stock: 12,
    status: "Active",
    desc: "Classic Monitor for office use",
    img: "https://picsum.photos/seed/p13/200/140",
  },
  {
    id: "p14",
    name: "Modern Cap",
    category: "Clothing",
    price: 25,
    stock: 100,
    status: "Inactive",
    desc: "Modern Cap for outdoor activities",
    img: "https://picsum.photos/seed/p14/200/140",
  },
  {
    id: "p15",
    name: "Stylish Keyboard",
    category: "Electronics",
    price: 79,
    stock: 45,
    status: "Active",
    desc: "Stylish Keyboard for typing",
    img: "https://picsum.photos/seed/p15/200/140",
  },
  {
    id: "p16",
    name: "Deluxe Socks",
    category: "Clothing",
    price: 15,
    stock: 200,
    status: "Inactive",
    desc: "Deluxe Socks for comfort",
    img: "https://picsum.photos/seed/p16/200/140",
  },
  {
    id: "p17",
    name: "Pro Drone",
    category: "Electronics",
    price: 599,
    stock: 5,
    status: "Active",
    desc: "Pro Drone for aerial photography",
    img: "https://picsum.photos/seed/p17/200/140",
  },
  {
    id: "p18",
    name: "Comfort Sweater",
    category: "Clothing",
    price: 55,
    stock: 40,
    status: "Inactive",
    desc: "Comfort Sweater for chilly days",
    img: "https://picsum.photos/seed/p18/200/140",
  },
  {
    id: "p19",
    name: "Ultra Smartphone",
    category: "Electronics",
    price: 899,
    stock: 18,
    status: "Active",
    desc: "Ultra Smartphone with latest tech",
    img: "https://picsum.photos/seed/p19/200/140",
  },
  {
    id: "p20",
    name: "Premium Scarf",
    category: "Clothing",
    price: 30,
    stock: 50,
    status: "Inactive",
    desc: "Premium Scarf for winter fashion",
    img: "https://picsum.photos/seed/p20/200/140",
  },
  {
    id: "p21",
    name: "Eco Laptop",
    category: "Electronics",
    price: 699,
    stock: 22,
    status: "Active",
    desc: "Eco Laptop for energy saving",
    img: "https://picsum.photos/seed/p21/200/140",
  },
  {
    id: "p22",
    name: "Stylish T-Shirt",
    category: "Clothing",
    price: 35,
    stock: 70,
    status: "Inactive",
    desc: "Stylish T-Shirt for everyday wear",
    img: "https://picsum.photos/seed/p22/200/140",
  },
  {
    id: "p23",
    name: "Classic Headphones",
    category: "Electronics",
    price: 129,
    stock: 32,
    status: "Active",
    desc: "Classic Headphones for music lovers",
    img: "https://picsum.photos/seed/p23/200/140",
  },
  {
    id: "p24",
    name: "Modern Jeans",
    category: "Clothing",
    price: 60,
    stock: 55,
    status: "Inactive",
    desc: "Modern Jeans for casual style",
    img: "https://picsum.photos/seed/p24/200/140",
  },
  {
    id: "p25",
    name: "Portable Camera",
    category: "Electronics",
    price: 449,
    stock: 14,
    status: "Active",
    desc: "Portable Camera for travel",
    img: "https://picsum.photos/seed/p25/200/140",
  },
  {
    id: "p26",
    name: "Deluxe Sneakers",
    category: "Clothing",
    price: 95,
    stock: 30,
    status: "Inactive",
    desc: "Deluxe Sneakers for comfort and style",
    img: "https://picsum.photos/seed/p26/200/140",
  },
  {
    id: "p27",
    name: "Pro Smartwatch",
    category: "Electronics",
    price: 279,
    stock: 28,
    status: "Active",
    desc: "Pro Smartwatch with health tracking",
    img: "https://picsum.photos/seed/p27/200/140",
  },
  {
    id: "p28",
    name: "Comfort Hoodie",
    category: "Clothing",
    price: 75,
    stock: 60,
    status: "Inactive",
    desc: "Comfort Hoodie for casual wear",
    img: "https://picsum.photos/seed/p28/200/140",
  },
  {
    id: "p29",
    name: "Deluxe Tablet",
    category: "Electronics",
    price: 399,
    stock: 20,
    status: "Active",
    desc: "Deluxe Tablet for work and play",
    img: "https://picsum.photos/seed/p29/200/140",
  },
  {
    id: "p30",
    name: "Stylish Dress",
    category: "Clothing",
    price: 80,
    stock: 45,
    status: "Inactive",
    desc: "Stylish Dress for casual or party",
    img: "https://picsum.photos/seed/p30/200/140",
  },
];
